### ISSUE TITLE
Wrong behaviour on load6 

### ISSUE THREAD

**Issue by xavortm** [lukehaas/css-loaders#11]
When the loader begin its cycle, the last 2-3 circles go back when they should start from point 0 (the top).

image: http://imageshack.com/a/img536/999/QU9wjA.jpg
Also, the ark is wrong and it doesnt follow the circle motion which make this particular loader look weird.

**Comment by lukehaas** [comment]
Hi xavortm,
Thanks for your observations.
This loader is definitely the most challenging of the eight to get right. 
I may update it at some point. You're also very welcome to make contributions.
