### ISSUE TITLE
Can I use it with white background page?

### ISSUE THREAD

**Issue by howtomakeaturn** [lukehaas/css-loaders#23]
Thanks for the awesome project!

My pages are white background. The loader becomes transparent on my site.

How to use the loader with white background page?

Thanks!

**Comment by rozhali** [comment]
hey Luke

There is a box-shadow in @keyframes load7, you could change the color there

**Comment by lukehaas** [comment]
Each .less file in the less folder has a variable called `foreground` this is where the colour is set for the loader. You can change this to any colour you want and then recompile the less.
