### ISSUE TITLE
Change spinner colour

### ISSUE THREAD

**Issue by Martin-Nyaga** [lukehaas/css-loaders#24]
Not really an issue, but a suggestion:

It would be great if there was a way to change the color of the spinning element directly from the css-loaders website. I have been doing it manually, and sometimes it isn't as straightforward as replacing the color codes especially for the spinners with rgba colors.

Otherwise, great tool.

**Comment by lukehaas** [comment]
Good idea. Take a look at the demo site now in Chrome or Firefox and you should see colour pickers.

**Comment by Martin-Nyaga** [comment]
Neat :+1:
