### ISSUE TITLE
Using load7 inside an aligned center (translate) div causes issue.

### ISSUE THREAD

**Issue by ImranBug** [lukehaas/css-loaders#27]
I have posted the question in detail on [stackoverflow](http://stackoverflow.com/questions/36625349/css-loaders-transform-box-shadow-animation-bug)

Basically `translate(-50%, -50%)` cutsoff the load7 animation from bottom.

**Comment by jakefreeberg** [comment]
@lukehaas : Looks like this got an answer and should be closed.
