### ISSUE TITLE
It is better if I can set the width and height with scss

### ISSUE THREAD

**Issue by hkkhchan** [lukehaas/css-loaders#33]
It is better if I can set the width and height with scss

**Comment by d4rkne55** [comment]
I don't agree with that.
I was in the process of creating a loader like here shortly before I discovered these ones and I did the same - reason being that you can give the border (the 'loading ring') a relative size then, as percentages don't work for borders.

For example giving the element a size of 1em and then wanting the border to be 15% of the element size - just give the border a size of 0.15em, that's it.
