### ISSUE TITLE
Adding a demo page?

### ISSUE THREAD

**Issue by stephnr** [lukehaas/css-loaders#4]

**Comment by ugogo** [comment]
http://projects.lukehaas.me/css-loaders/
It's in the README.

**Comment by mengstr** [comment]
No, there's no link to the demo page in the README.md.....

**Comment by ugogo** [comment]
![capture decran 2014-05-28 a 14 18 07](https://cloud.githubusercontent.com/assets/5040476/3104082/3040fd04-e662-11e3-80e5-fcdd08c46d1c.png)

**Comment by mengstr** [comment]
That is not visible in the README.md I see.
![screen shot 2014-05-28 at 20 19 28](https://cloud.githubusercontent.com/assets/325326/3104111/87b6ba1a-e662-11e3-82fc-42290d980e5b.png)

**Comment by ugogo** [comment]
And what about clicking on the title, mh ?

**Comment by mengstr** [comment]
Meh....  How could anyone guess that clicking the heading in the readme would take take you to the demo?  That is just as clear as having a picture of a cat in the readme that is linked to the demo and expect people to just click on random stuff in the hopes of a demo.

I'm sure (hope at least) that this is just a oversight of the author.

**Comment by ugogo** [comment]
@SmallRoomLabs :-)

**Comment by lukehaas** [comment]
@SmallRoomLabs it is a convention on the web for links to be blue. The title of the readme is clearly a link, and there's nothing it would logically link to other than a demo page.
I don't see a need to make a change here.

**Comment by mengstr** [comment]
@lukehaas Sorry, I don't want to sound like an ass, but yes, I know that blue underlines words are links, and apparently there seems to be others that are just as stupid as me and didn't understand that a heading with the name of the product leads to a demo page.  Usually a link is indicating where it will take you - either with an icon or some relevant word(s).  And I'd also have to say that it's definitely not a convention to have a header as a link to an offsite page.

But you do as you please, it's your product. I can't tell you what to do. I can only tell you that although I have spent hours upon hours every day for the last 20 years I'm apparently too dense to be able to find the demo link.

Anyho, I like the product and will most def use it.  Thanks for making it.

**Comment by lukehaas** [comment]
@SmallRoomLabs ok, I've added another link to the demo page to make it clearer.
Thanks for bringing this issue to my attention.
